// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_AirPlane.Models;

namespace WebApp_AirPlane.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200118010653_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp_AirPlane.Controllers.Airplane", b =>
                {
                    b.Property<int>("IdAviao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CapacCarga");

                    b.Property<int>("CapacPassageiros");

                    b.Property<string>("Modelo");

                    b.Property<int>("QtdTurbinas");

                    b.HasKey("IdAviao");

                    b.ToTable("AirPlane");
                });

            modelBuilder.Entity("WebApp_AirPlane.Controllers.Passengers", b =>
                {
                    b.Property<int>("IdPassageiro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Estado");

                    b.Property<int>("IdAviao");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Municipio");

                    b.Property<string>("Nome");

                    b.Property<string>("Numero");

                    b.Property<string>("Telefone");

                    b.HasKey("IdPassageiro");

                    b.HasIndex("IdAviao");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("WebApp_AirPlane.Controllers.Passengers", b =>
                {
                    b.HasOne("WebApp_AirPlane.Controllers.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("IdAviao")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
